/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package test;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author My PC
 */
public class Dialog extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Dialog() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        themNV_jDialog = new JDialog();
        jPanel3 = new JPanel();
        cancel_themNV_jButton = new JButton();
        idNhanVien_jLabel = new javax.swing.JLabel();
        hoTen__jLabel = new javax.swing.JLabel();
        cccd_jLabel = new javax.swing.JLabel();
        soDienThoai_jLabel = new javax.swing.JLabel();
        gioi_Tinh_jLabel = new javax.swing.JLabel();
        eMail_jLabel = new javax.swing.JLabel();
        ngaySinh_jLabel = new javax.swing.JLabel();
        chucVu_jLabel = new javax.swing.JLabel();
        ngayVaoLam_jLabel = new javax.swing.JLabel();
        luong_jLabel = new javax.swing.JLabel();
        diaChi_jLabel = new javax.swing.JLabel();
        idNhanVien_jTextField = new javax.swing.JTextField();
        hoTen_jTextField = new javax.swing.JTextField();
        cccd_jTextField = new javax.swing.JTextField();
        soDienThoai_jTextField = new javax.swing.JTextField();
        gioiTinh_jTextField = new javax.swing.JTextField();
        eMaill_jTextField = new javax.swing.JTextField();
        ngaySinh_jTextField = new javax.swing.JTextField();
        chucVu_jTextField = new javax.swing.JTextField();
        ngayVaoLam_jTextField = new javax.swing.JTextField();
        luong_jTextField = new javax.swing.JTextField();
        diaChi_jTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nhanVien_jButton = new javax.swing.JButton();
        khachHang_jButton = new javax.swing.JButton();
        hoaDon_jButton = new javax.swing.JButton();
        thucDon_jButton = new javax.swing.JButton();
        kho_jButton = new javax.swing.JButton();

        themNV_jDialog.setBackground(new java.awt.Color(255, 255, 255));
        themNV_jDialog.setMinimumSize(new java.awt.Dimension(600, 450));
        themNV_jDialog.setModal(true);
        themNV_jDialog.setResizable(false);
        java.awt.GridBagLayout themNV_jDialogLayout = new java.awt.GridBagLayout();
        themNV_jDialogLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        themNV_jDialogLayout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        themNV_jDialog.getContentPane().setLayout(themNV_jDialogLayout);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        themNV_jDialog.getContentPane().add(jPanel3, gridBagConstraints);

        cancel_themNV_jButton.setText("HỦY");
        cancel_themNV_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_themNV_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 68;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        themNV_jDialog.getContentPane().add(cancel_themNV_jButton, gridBagConstraints);

        idNhanVien_jLabel.setText("ID Nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(idNhanVien_jLabel, gridBagConstraints);

        hoTen__jLabel.setText("CMND/CCCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(hoTen__jLabel, gridBagConstraints);

        cccd_jLabel.setText("Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(cccd_jLabel, gridBagConstraints);

        soDienThoai_jLabel.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(soDienThoai_jLabel, gridBagConstraints);

        gioi_Tinh_jLabel.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(gioi_Tinh_jLabel, gridBagConstraints);

        eMail_jLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(eMail_jLabel, gridBagConstraints);

        ngaySinh_jLabel.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(ngaySinh_jLabel, gridBagConstraints);

        chucVu_jLabel.setText("Chức vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(chucVu_jLabel, gridBagConstraints);

        ngayVaoLam_jLabel.setText("Ngày vào làm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(ngayVaoLam_jLabel, gridBagConstraints);

        luong_jLabel.setText("Lương");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(luong_jLabel, gridBagConstraints);

        diaChi_jLabel.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        themNV_jDialog.getContentPane().add(diaChi_jLabel, gridBagConstraints);

        idNhanVien_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNhanVien_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(idNhanVien_jTextField, gridBagConstraints);

        hoTen_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTen_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(hoTen_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(cccd_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(soDienThoai_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(gioiTinh_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(eMaill_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(ngaySinh_jTextField, gridBagConstraints);

        chucVu_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chucVu_jTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(chucVu_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(ngayVaoLam_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(luong_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 49;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        themNV_jDialog.getContentPane().add(diaChi_jTextField, gridBagConstraints);

        jButton1.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 58;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        themNV_jDialog.getContentPane().add(jButton1, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("quanLyNhanVien_jFrame");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        kGradientPanel2.setBackground(new Color(167, 223, 255));
        kGradientPanel2.setLayout(new java.awt.GridLayout(6, 1));

        nhanVien_jButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        nhanVien_jButton.setHorizontalTextPosition(SwingConstants.CENTER);
        nhanVien_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/image/btnNV.png"));
        java.awt.Image image = icon.getImage().getScaledInstance(70, 70, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon newIcon = new javax.swing.ImageIcon(image);
        nhanVien_jButton.setIcon(newIcon);
        nhanVien_jButton.setText("NHÂN VIÊN");
        nhanVien_jButton.setOpaque(false);
        nhanVien_jButton.setContentAreaFilled(false);
        nhanVien_jButton.setBorderPainted(false);
        nhanVien_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVien_jButtonActionPerformed(evt);
            }
        });
        kGradientPanel2.add(nhanVien_jButton);

        khachHang_jButton.setOpaque(false);
        khachHang_jButton.setContentAreaFilled(false);
        khachHang_jButton.setBorderPainted(false);
        khachHang_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        khachHang_jButton.setText("KHÁCH HÀNG");
        khachHang_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHang_jButtonActionPerformed(evt);
            }
        });
        kGradientPanel2.add(khachHang_jButton);

        hoaDon_jButton.setOpaque(false);
        hoaDon_jButton.setContentAreaFilled(false);
        hoaDon_jButton.setBorderPainted(false);
        hoaDon_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoaDon_jButton.setText("HÓA ĐƠN");
        kGradientPanel2.add(hoaDon_jButton);

        thucDon_jButton.setOpaque(false);
        thucDon_jButton.setContentAreaFilled(false);
        thucDon_jButton.setBorderPainted(false);
        thucDon_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thucDon_jButton.setText("THỰC ĐƠN");
        kGradientPanel2.add(thucDon_jButton);

        kho_jButton.setOpaque(false);
        kho_jButton.setContentAreaFilled(false);
        kho_jButton.setBorderPainted(false);
        kho_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kho_jButton.setText("KHO");
        kGradientPanel2.add(kho_jButton);

        getContentPane().add(kGradientPanel2, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_themNV_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_themNV_jButtonActionPerformed
        // TODO add your handling code here:
        themNV_jDialog.setVisible(false);
    }//GEN-LAST:event_cancel_themNV_jButtonActionPerformed

    private void hoTen_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTen_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTen_jTextFieldActionPerformed

    private void idNhanVien_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNhanVien_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNhanVien_jTextFieldActionPerformed

    private void chucVu_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chucVu_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chucVu_jTextFieldActionPerformed

    private void khachHang_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHang_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachHang_jButtonActionPerformed

    private void nhanVien_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVien_jButtonActionPerformed
        // TODO add your handling code here:
        themNV_jDialog.pack();
        themNV_jDialog.setLocationRelativeTo(null);
        themNV_jDialog.setVisible(true);
    }//GEN-LAST:event_nhanVien_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_themNV_jButton;
    private javax.swing.JLabel cccd_jLabel;
    private javax.swing.JTextField cccd_jTextField;
    private javax.swing.JLabel chucVu_jLabel;
    private javax.swing.JTextField chucVu_jTextField;
    private javax.swing.JLabel diaChi_jLabel;
    private javax.swing.JTextField diaChi_jTextField;
    private javax.swing.JLabel eMail_jLabel;
    private javax.swing.JTextField eMaill_jTextField;
    private javax.swing.JTextField gioiTinh_jTextField;
    private javax.swing.JLabel gioi_Tinh_jLabel;
    private javax.swing.JLabel hoTen__jLabel;
    private javax.swing.JTextField hoTen_jTextField;
    private javax.swing.JButton hoaDon_jButton;
    private javax.swing.JLabel idNhanVien_jLabel;
    private javax.swing.JTextField idNhanVien_jTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private JPanel kGradientPanel2 = new JPanel();
    private javax.swing.JButton khachHang_jButton;
    private javax.swing.JButton kho_jButton;
    private javax.swing.JLabel luong_jLabel;
    private javax.swing.JTextField luong_jTextField;
    private javax.swing.JLabel ngaySinh_jLabel;
    private javax.swing.JTextField ngaySinh_jTextField;
    private javax.swing.JLabel ngayVaoLam_jLabel;
    private javax.swing.JTextField ngayVaoLam_jTextField;
    private javax.swing.JButton nhanVien_jButton;
    private javax.swing.JLabel soDienThoai_jLabel;
    private javax.swing.JTextField soDienThoai_jTextField;
    private javax.swing.JDialog themNV_jDialog;
    private javax.swing.JButton thucDon_jButton;
    // End of variables declaration//GEN-END:variables
}
