/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        thanhBen1 = new view.ThanhBen();
        pane_bg = new javax.swing.JPanel();
        pane_HoaDon = new javax.swing.JPanel();
        pane_SoHD_SoBan = new javax.swing.JPanel();
        label_SetSoHD = new javax.swing.JLabel();
        label_SetSoBan = new javax.swing.JLabel();
        btn_ThucDon = new view.ButtonGradient();
        CheckBox_DaThanhToan = new javax.swing.JCheckBox();
        label_TongTien = new javax.swing.JLabel();
        label_SetTongTien = new javax.swing.JLabel();
        btn_InHoaDon = new view.ButtonGradient();
        btn_ThanhToan = new view.ButtonGradient();
        ScrollPane_CTHD = new javax.swing.JScrollPane();
        Object[][] data = {};
        String[] columnNames = {"", "", ""};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        table_CTHD = new javax.swing.JTable(model);
        pane_Chung = new javax.swing.JPanel();
        pane_btn = new javax.swing.JPanel();
        btn_ViTri = new view.ButtonGradient();
        btn_LichSuHD = new view.ButtonGradient();
        pane_bg_ViTri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));

        pane_bg.setBackground(new java.awt.Color(204, 204, 204));
        pane_bg.setPreferredSize(new java.awt.Dimension(100, 600));

        pane_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pane_HoaDon.setPreferredSize(new java.awt.Dimension(270, 490));
        pane_HoaDon.setLayout(new java.awt.GridBagLayout());

        pane_SoHD_SoBan.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        pane_SoHD_SoBan.setPreferredSize(new java.awt.Dimension(120, 30));
        pane_SoHD_SoBan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        label_SetSoHD.setBackground(new java.awt.Color(130, 210, 255));
        label_SetSoHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_SetSoHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_SetSoHD.setText("HD001");
        label_SetSoHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_SetSoHD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_SetSoHD.setIconTextGap(0);
        label_SetSoHD.setMinimumSize(new java.awt.Dimension(50, 20));
        label_SetSoHD.setOpaque(true);
        label_SetSoHD.setPreferredSize(new java.awt.Dimension(70, 30));
        pane_SoHD_SoBan.add(label_SetSoHD);

        label_SetSoBan.setBackground(new java.awt.Color(225, 244, 255));
        label_SetSoBan.setForeground(new java.awt.Color(0, 102, 255));
        label_SetSoBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_SetSoBan.setText("Bàn 1");
        label_SetSoBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_SetSoBan.setIconTextGap(0);
        label_SetSoBan.setOpaque(true);
        label_SetSoBan.setPreferredSize(new java.awt.Dimension(50, 30));
        pane_SoHD_SoBan.add(label_SetSoBan);

        pane_HoaDon.add(pane_SoHD_SoBan, new java.awt.GridBagConstraints());

        btn_ThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar1.png"))); // NOI18N
        btn_ThucDon.setText("Thực đơn");
        btn_ThucDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ThucDon.setPreferredSize(new java.awt.Dimension(118, 33));
        btn_ThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThucDonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pane_HoaDon.add(btn_ThucDon, gridBagConstraints);

        CheckBox_DaThanhToan.setText("Đã thanh toán");
        CheckBox_DaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_DaThanhToanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pane_HoaDon.add(CheckBox_DaThanhToan, gridBagConstraints);

        label_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_TongTien.setText("TỔNG TIỀN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pane_HoaDon.add(label_TongTien, gridBagConstraints);

        label_SetTongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_SetTongTien.setText("300000");
        label_SetTongTien.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pane_HoaDon.add(label_SetTongTien, gridBagConstraints);

        btn_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar1.png"))); // NOI18N
        btn_InHoaDon.setText("In hóa đơn");
        btn_InHoaDon.setPreferredSize(new java.awt.Dimension(118, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pane_HoaDon.add(btn_InHoaDon, gridBagConstraints);

        btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar1.png"))); // NOI18N
        btn_ThanhToan.setText("Thanh toán");
        btn_ThanhToan.setPreferredSize(new java.awt.Dimension(125, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pane_HoaDon.add(btn_ThanhToan, gridBagConstraints);

        ScrollPane_CTHD.setPreferredSize(new java.awt.Dimension(250, 320));

        table_CTHD.setModel(model);
        ScrollPane_CTHD.setViewportView(table_CTHD);
        table_CTHD.setPreferredScrollableViewportSize(table_CTHD.getPreferredSize());
        table_CTHD.setTableHeader(null);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        pane_HoaDon.add(ScrollPane_CTHD, gridBagConstraints);

        pane_bg.add(pane_HoaDon);

        pane_Chung.setBackground(new java.awt.Color(204, 204, 204));
        pane_Chung.setAlignmentX(0.0F);
        pane_Chung.setAlignmentY(0.0F);
        pane_Chung.setPreferredSize(new java.awt.Dimension(500, 500));

        pane_btn.setBackground(new java.awt.Color(255, 255, 255));
        pane_btn.setAlignmentX(0.0F);
        pane_btn.setAlignmentY(0.0F);
        pane_btn.setPreferredSize(new java.awt.Dimension(500, 50));
        pane_btn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        btn_ViTri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar1.png"))); // NOI18N
        btn_ViTri.setText("Vị trí");
        btn_ViTri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ViTri.setPreferredSize(new java.awt.Dimension(100, 33));
        btn_ViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViTriActionPerformed(evt);
            }
        });
        pane_btn.add(btn_ViTri);

        btn_LichSuHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/history.png"))); // NOI18N
        btn_LichSuHD.setText("Lịch sử hóa đơn");
        btn_LichSuHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_LichSuHD.setMaximumSize(new java.awt.Dimension(100, 27));
        btn_LichSuHD.setMinimumSize(new java.awt.Dimension(100, 27));
        btn_LichSuHD.setPreferredSize(new java.awt.Dimension(150, 33));
        pane_btn.add(btn_LichSuHD);

        pane_Chung.add(pane_btn);

        pane_bg_ViTri.setBackground(new java.awt.Color(255, 255, 255));
        pane_bg_ViTri.setPreferredSize(new java.awt.Dimension(500, 435));
        pane_bg_ViTri.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4);

        jButton4.setText("jButton4");
        jPanel1.add(jButton4);

        jButton5.setText("jButton5");
        jPanel1.add(jButton5);

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);

        jScrollPane1.setViewportView(jPanel1);

        pane_bg_ViTri.add(jScrollPane1);

        pane_Chung.add(pane_bg_ViTri);

        pane_bg.add(pane_Chung);

        getContentPane().add(pane_bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThucDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThucDonActionPerformed

    private void CheckBox_DaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_DaThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_DaThanhToanActionPerformed

    private void btn_ViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViTriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatArcIJTheme());

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_DaThanhToan;
    private javax.swing.JScrollPane ScrollPane_CTHD;
    private view.ButtonGradient btn_InHoaDon;
    private view.ButtonGradient btn_LichSuHD;
    private view.ButtonGradient btn_ThanhToan;
    private view.ButtonGradient btn_ThucDon;
    private view.ButtonGradient btn_ViTri;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel label_SetSoBan;
    private javax.swing.JLabel label_SetSoHD;
    private javax.swing.JLabel label_SetTongTien;
    private javax.swing.JLabel label_TongTien;
    private javax.swing.JPanel pane_Chung;
    private javax.swing.JPanel pane_HoaDon;
    private javax.swing.JPanel pane_SoHD_SoBan;
    private javax.swing.JPanel pane_bg;
    private javax.swing.JPanel pane_bg_ViTri;
    private javax.swing.JPanel pane_btn;
    private javax.swing.JTable table_CTHD;
    private view.ThanhBen thanhBen1;
    // End of variables declaration//GEN-END:variables
}
